github: Disable Microsoft apt repos.
We don't use them, and their presence may cause transient failures
sometimes, e.g.:

```
Reading package lists...
E: Failed to fetch https://packages.microsoft.com/[...]  403  Forbidden [IP: ...]
E: The repository 'https://packages.microsoft.com/[...]' is no longer signed.
Error: Process completed with exit code 100.
```

Signed-off-by: Ihar Hrachyshka <ihrachyshka@nvidia.com>